-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointments
(
    id serial NOT NULL,
    user_id integer,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    duration integer NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    availability jsonb DEFAULT '[]'::jsonb,
    admin boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS public.doctors
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    specialization character varying(255) COLLATE pg_catalog."default" NOT NULL,
    availability jsonb DEFAULT '[]'::jsonb,
    CONSTRAINT doctors_pkey PRIMARY KEY (id)
);

ALTER TABLE public.users
ADD COLUMN sex character varying(10) COLLATE pg_catalog."default",
ADD COLUMN firstname character varying(255) COLLATE pg_catalog."default",
ADD COLUMN lastname character varying(255) COLLATE pg_catalog."default";


ALTER TABLE IF EXISTS public.users
ADD COLUMN phone character varying(255) COLLATE pg_catalog."default";


END;